// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// prml
void prml();
RcppExport SEXP rpacktest_prml() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    prml();
    return R_NilValue;
END_RCPP
}
// timesTwo
Rcpp::NumericVector timesTwo(Rcpp::NumericVector x);
RcppExport SEXP rpacktest_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(timesTwo(x));
    return __result;
END_RCPP
}
// perfumeNames
void perfumeNames();
RcppExport SEXP rpacktest_perfumeNames() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    perfumeNames();
    return R_NilValue;
END_RCPP
}
