// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// prml
void prml();
RcppExport SEXP rpacktest_prml() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    prml();
    return R_NilValue;
END_RCPP
}
// timesTwo
Rcpp::NumericVector timesTwo(Rcpp::NumericVector x);
RcppExport SEXP rpacktest_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// perfumeNames
void perfumeNames();
RcppExport SEXP rpacktest_perfumeNames() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    perfumeNames();
    return R_NilValue;
END_RCPP
}
