# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Declares that I read a famous textbook.
#' @export
prml <- function() {
    invisible(.Call('rpacktest_prml', PACKAGE = 'rpacktest'))
}

timesTwo <- function(x) {
    .Call('rpacktest_timesTwo', PACKAGE = 'rpacktest', x)
}

#' Perfume members introduce themselves on your console
#' @export
perfumeNames <- function() {
    invisible(.Call('rpacktest_perfumeNames', PACKAGE = 'rpacktest'))
}

